[phases.setup]
nixPkgs = ['nodejs-18_x', 'nginx']

[phases.build]
cmds = [
    'cd frontend',
    'echo "legacy-peer-deps=true" > .npmrc',
    'echo "auto-install-peers=true" >> .npmrc', 
    'npm install --legacy-peer-deps',
    'NODE_OPTIONS="--openssl-legacy-provider" npm run build',
    'cp -r build/* ../public/'
]

[start]
cmd = 'nginx -g "daemon off;"'

[variables]
NODE_ENV = 'production'